const supportedPortals = ['user', 'courier', 'cafe'];
const requestedPortal = (process.env.REACT_APP_PORTAL || 'user').toLowerCase();

export const PORTAL = supportedPortals.includes(requestedPortal) ? requestedPortal : 'user';

const portalMetaMap = {
    user: {
        key: 'user',
        role: 'USER',
        label: 'Client',
        portalLabel: 'Client portal',
        portalSubtitle: 'Customer authentication, ordering, and order history run in a dedicated frontend instance.',
        loginRoute: '/login',
        registerRoute: '/register',
        afterLoginRoute: '/client-order',
        dashboardLabel: 'Order',
        dashboardRoute: '/client-order',
        secondaryRoute: '/user-orders',
        secondaryLabel: 'History',
        loginTitle: 'Login',
        loginSubtitle: 'Access your customer account',
        loginAccentTitle: 'Welcome back',
        loginAccentText: 'Enter the client workspace to create orders, review history, and manage your delivery flow.',
        registerTitle: 'Register',
        registerSubtitle: 'Create your customer account',
        registerAccentTitle: 'New here?',
        registerAccentText: 'Register once, then use the client portal for ordering and order tracking.',
        switchToRegisterLabel: 'Signup',
        switchToLoginLabel: 'Login',
    },
    courier: {
        key: 'courier',
        role: 'COURIER',
        label: 'Courier',
        portalLabel: 'Courier portal',
        portalSubtitle: 'Courier authentication and delivery workflow run in a separate frontend instance.',
        loginRoute: '/login',
        registerRoute: '/register',
        afterLoginRoute: '/courier-dashboard',
        dashboardLabel: 'Dashboard',
        dashboardRoute: '/courier-dashboard',
        secondaryRoute: '/courier',
        secondaryLabel: 'Request',
        loginTitle: 'Login',
        loginSubtitle: 'Access the courier workspace',
        loginAccentTitle: 'Welcome back',
        loginAccentText: 'Sign in to accept deliveries, monitor active orders, and manage your courier session.',
        registerTitle: 'Register',
        registerSubtitle: 'Create your courier account',
        registerAccentTitle: 'Join delivery flow',
        registerAccentText: 'Create a courier account and continue into the dispatch workspace.',
        switchToRegisterLabel: 'Signup',
        switchToLoginLabel: 'Login',
    },
    cafe: {
        key: 'cafe',
        role: 'CAFE',
        label: 'Cafe',
        portalLabel: 'Cafe portal',
        portalSubtitle: 'Cafe administration and order management run in their own frontend instance.',
        loginRoute: '/login',
        registerRoute: '/register',
        afterLoginRoute: '/cafe-admin',
        dashboardLabel: 'Admin',
        dashboardRoute: '/cafe-admin',
        secondaryRoute: '/cafe-orders',
        secondaryLabel: 'Orders',
        loginTitle: 'Login',
        loginSubtitle: 'Access the cafe workspace',
        loginAccentTitle: 'Welcome back',
        loginAccentText: 'Continue to cafe administration, menu management, districts, and incoming orders.',
        registerTitle: 'Register',
        registerSubtitle: 'Create your cafe account',
        registerAccentTitle: 'Open your workspace',
        registerAccentText: 'Create the merchant profile and continue into the cafe control panel.',
        switchToRegisterLabel: 'Signup',
        switchToLoginLabel: 'Login',
    },
};

export const PORTAL_META = portalMetaMap[PORTAL];
